name: Build and Deploy to Dev

on:
  push:
    branches:
      - dev
      - faisal-dev

jobs:
  deploy:
    name: SSH Deploy to Namecheap (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}           # e.g. professor.website or 209.74.67.43
          username: ${{ secrets.USERNAME }}       # e.g. proflxlj
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # paste PRIVATE key in GitHub Secrets
          port: ${{ secrets.PORT }}               # e.g. 21098 (Namecheap default)
          script: |
                cd ${{ secrets.PATH }}
                chmod +x deploy-dev.sh
                ./deploy-dev.sh
