name: Build and Deploy to Dev

on:
  push:
    branches:
      - dev
      - faisal-dev

jobs:
  deploy:
    name: SSH Deploy to Namecheap (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
                cd ${{ secrets.PATH }}
                chmod +x deploy-dev.sh
                ./deploy-dev.sh
