name: Build and Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: SSH Deploy to Namecheap (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}           # e.g. professor.website or 209.74.67.43
          username: ${{ secrets.USERNAME }}       # e.g. proflxlj
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # your private key
          port: ${{ secrets.PORT }}               # usually 21098 for Namecheap
          script: |
            cd ${{ secrets.PATH }} && ./deploy-dev.sh